const airportsData = {
  "airports": [
    {
      "IATA_code": "AGX",
      "ICAO_code": "VOAT",
      "airport_name": "Agatti Island Airport",
      "city_name": "Agatti Island"
    },
    {
      "IATA_code": "AMD",
      "ICAO_code": "VAAH",
      "airport_name": "Ahmedabad Airport",
      "city_name": "Ahmedabad"
    },
    {
      "IATA_code": "AJL",
      "ICAO_code": "VEAZ",
      "airport_name": "Aizawl Airport",
      "city_name": "Aizawl"
    },
    {
      "IATA_code": "AKD",
      "ICAO_code": "VAAK",
      "airport_name": "Akola Airport",
      "city_name": "Akola"
    },
    {
      "IATA_code": "IXV",
      "ICAO_code": "VEAN",
      "airport_name": "Along Airport",
      "city_name": "Along"
    },
    {
      "IATA_code": "LKO",
      "ICAO_code": "VILK",
      "airport_name": "Amausi Airport",
      "city_name": "Lucknow"
    },
    {
      "IATA_code": "LUH",
      "ICAO_code": "VILD",
      "airport_name": "Amritsar Airport",
      "city_name": "Ludhiana"
    },
    {
      "IATA_code": "IXB",
      "ICAO_code": "VEBD",
      "airport_name": "Bagdogra Airport",
      "city_name": "Bagdogra"
    },
    {
      "IATA_code": "IXE",
      "ICAO_code": "VOML",
      "airport_name": "Bajpe Airport",
      "city_name": "Mangalore"
    },
    {
      "IATA_code": "IXL",
      "ICAO_code": "VILH",
      "airport_name": "Bakula Rimpoche Airport",
      "city_name": "Leh"
    },
    {
      "IATA_code": "RGH",
      "ICAO_code": "VEBG",
      "airport_name": "Balurghat Airport",
      "city_name": "Balurghat"
    },
    {
      "IATA_code": "IXD",
      "ICAO_code": "VIAL",
      "airport_name": "Bamrauli Airport",
      "city_name": "Allahabad"
    },
    {
      "IATA_code": "SHL",
      "ICAO_code": "VEBI",
      "airport_name": "Barapani Airport",
      "city_name": "Shillong"
    },
    {
      "IATA_code": "BEK",
      "ICAO_code": "VOPN",
      "airport_name": "Bareli Airport",
      "city_name": "Bareli"
    },
    {
      "IATA_code": "BEP",
      "ICAO_code": "VOBI",
      "airport_name": "Bellary Airport",
      "city_name": "Bellary"
    },
    {
      "IATA_code": "BLR",
      "ICAO_code": "VOBG",
      "airport_name": "Bengaluru International Airport",
      "city_name": "Bangalore"
    },
    {
      "IATA_code": "BUP",
      "ICAO_code": "VIBT",
      "airport_name": "Bhatinda Airport",
      "city_name": "Bhatinda"
    },
    {
      "IATA_code": "BHU",
      "ICAO_code": "VABV",
      "airport_name": "Bhavnagar Airport",
      "city_name": "Bhavnagar"
    },
    {
      "IATA_code": "BHO",
      "ICAO_code": "VABP",
      "airport_name": "Bhopal Airport",
      "city_name": "Bhopal"
    },
    {
      "IATA_code": "BBI",
      "ICAO_code": "VEBS",
      "airport_name": "Bhubaneswar Airport",
      "city_name": "Bhubaneswar"
    },
    {
      "IATA_code": "BKB",
      "ICAO_code": "VIBK",
      "airport_name": "Bikaner Airport",
      "city_name": "Bikaner"
    },
    {
      "IATA_code": "PAB",
      "ICAO_code": "VABI",
      "airport_name": "Bilaspur Airport",
      "city_name": "Bilaspur"
    },
    {
      "IATA_code": "IXR",
      "ICAO_code": "VERC",
      "airport_name": "Birsa Munda International Airport",
      "city_name": "Ranchi"
    },
    {
      "IATA_code": "GAU",
      "ICAO_code": "VEGT",
      "airport_name": "Borjhar Airport",
      "city_name": "Guwahati"
    },
    {
      "IATA_code": "CBD",
      "ICAO_code": "VECX",
      "airport_name": "Car Nicobar Airport",
      "city_name": "Car Nicobar"
    },
    {
      "IATA_code": "IXC",
      "ICAO_code": "VICG",
      "airport_name": "Chandigarh Airport",
      "city_name": "Chandigarh"
    },
    {
      "IATA_code": "MAA",
      "ICAO_code": "VOMM",
      "airport_name": "Chennai International Airport",
      "city_name": "Chennai"
    },
    {
      "IATA_code": "BOM",
      "ICAO_code": "VABB",
      "airport_name": "Chhatrapati Shivaji International Airport",
      "city_name": "Mumbai"
    },
    {
      "IATA_code": "IXU",
      "ICAO_code": "VAAU",
      "airport_name": "Chikkalthana Airport",
      "city_name": "Aurangabad"
    },
    {
      "IATA_code": "COK",
      "ICAO_code": "VOCI",
      "airport_name": "Cochin International Airport",
      "city_name": "Kochi"
    },
    {
      "IATA_code": "COH",
      "ICAO_code": "VECO",
      "airport_name": "Cooch Behar Airport",
      "city_name": "Cooch Behar"
    },
    {
      "IATA_code": "CDP",
      "ICAO_code": "VOCP",
      "airport_name": "Cuddapah Airport",
      "city_name": "Cuddapah"
    },
    {
      "IATA_code": "UDR",
      "ICAO_code": "VAUD",
      "airport_name": "Dabok Airport",
      "city_name": "Udaipur"
    },
    {
      "IATA_code": "GOI",
      "ICAO_code": "VAGO",
      "airport_name": "Dabolim Airport",
      "city_name": "Goa"
    },
    {
      "IATA_code": "NMB",
      "ICAO_code": "VADN",
      "airport_name": "Daman Airport",
      "city_name": "Daman"
    },
    {
      "IATA_code": "DAE",
      "ICAO_code": "VEDZ",
      "airport_name": "Daparizo Airport",
      "city_name": "Daparizo"
    },
    {
      "IATA_code": "DAI",
      "ICAO_code": "",
      "airport_name": "Darjeeling Airport",
      "city_name": "Darjeeling"
    },
    {
      "IATA_code": "DED",
      "ICAO_code": "VIDN",
      "airport_name": "Dehra Dun Airport",
      "city_name": "Dehra Dun"
    },
    {
      "IATA_code": "DEP",
      "ICAO_code": "",
      "airport_name": "Deparizo Airport",
      "city_name": "Deparizo"
    },
    {
      "IATA_code": "IDR",
      "ICAO_code": "VAID",
      "airport_name": "Devi Ahilyabai Holkar Airport",
      "city_name": "Indore"
    },
    {
      "IATA_code": "DBD",
      "ICAO_code": "VEDB",
      "airport_name": "Dhanbad Airport",
      "city_name": "Dhanbad"
    },
    {
      "IATA_code": "DIB",
      "ICAO_code": "VEMN",
      "airport_name": "Dibrugarh Airport",
      "city_name": "Dibrugarh"
    },
    {
      "IATA_code": "DMU",
      "ICAO_code": "VEMR",
      "airport_name": "Dimapur Airport",
      "city_name": "Dimapur"
    },
    {
      "IATA_code": "DIU",
      "ICAO_code": "VA1P",
      "airport_name": "Diu Airport",
      "city_name": "Diu"
    },
    {
      "IATA_code": "DHM",
      "ICAO_code": "VIGG",
      "airport_name": "Gaggal Airport",
      "city_name": "Dharamsala"
    },
    {
      "IATA_code": "ISK",
      "ICAO_code": "VANR",
      "airport_name": "Gandhinagar Airport",
      "city_name": "Nasik"
    },
    {
      "IATA_code": "GAY",
      "ICAO_code": "VEGY",
      "airport_name": "Gaya Airport",
      "city_name": "Gaya"
    },
    {
      "IATA_code": "GOP",
      "ICAO_code": "VEGK",
      "airport_name": "Gorakhpur Airport",
      "city_name": "Gorakhpur"
    },
    {
      "IATA_code": "JGA",
      "ICAO_code": "VAJM",
      "airport_name": "Govardhanpur Airport",
      "city_name": "Jamnagar"
    },
    {
      "IATA_code": "GUX",
      "ICAO_code": "VAGN",
      "airport_name": "Guna Airport",
      "city_name": "Guna"
    },
    {
      "IATA_code": "GWL",
      "ICAO_code": "VIGR",
      "airport_name": "Gwalior Airport",
      "city_name": "Gwalior"
    },
    {
      "IATA_code": "HSS",
      "ICAO_code": "VIHR",
      "airport_name": "Hissar Airport",
      "city_name": "Hissar"
    },
    {
      "IATA_code": "HBX",
      "ICAO_code": "VAHB",
      "airport_name": "Hubli Airport",
      "city_name": "Hubli"
    },
    {
      "IATA_code": "HYD",
      "ICAO_code": "VOHY",
      "airport_name": "Hyderabad International Airport",
      "city_name": "Hyderabad"
    },
    {
      "IATA_code": "DEL",
      "ICAO_code": "VIDP",
      "airport_name": "Indira Gandhi International Airport",
      "city_name": "New Delhi"
    },
    {
      "IATA_code": "JLR",
      "ICAO_code": "VAJB",
      "airport_name": "Jabalpur Airport",
      "city_name": "Jabalpur"
    },
    {
      "IATA_code": "JGB",
      "ICAO_code": "",
      "airport_name": "Jagdalpur Airport",
      "city_name": "Jagdalpur"
    },
    {
      "IATA_code": "JSA",
      "ICAO_code": "VIJR",
      "airport_name": "Jaisalmer Airport",
      "city_name": "Jaisalmer"
    },
    {
      "IATA_code": "PYB",
      "ICAO_code": "VEJP",
      "airport_name": "Jeypore Airport",
      "city_name": "Jeypore"
    },
    {
      "IATA_code": "JDH",
      "ICAO_code": "VIJO",
      "airport_name": "Jodhpur Airport",
      "city_name": "Jodhpur"
    },
    {
      "IATA_code": "IXH",
      "ICAO_code": "VEKR",
      "airport_name": "Kailashahar Airport",
      "city_name": "Kailashahar"
    },
    {
      "IATA_code": "IXQ",
      "ICAO_code": "VEKM",
      "airport_name": "Kamalpur Airport",
      "city_name": "Kamalpur"
    },
    {
      "IATA_code": "IXY",
      "ICAO_code": "VAKE",
      "airport_name": "Kandla Airport",
      "city_name": "Kandla"
    },
    {
      "IATA_code": "KNU",
      "ICAO_code": "VIKA",
      "airport_name": "Kanpur Airport",
      "city_name": "Kanpur"
    },
    {
      "IATA_code": "IXK",
      "ICAO_code": "VAKS",
      "airport_name": "Keshod Airport",
      "city_name": "Keshod"
    },
    {
      "IATA_code": "HJR",
      "ICAO_code": "VAKJ",
      "airport_name": "Khajuraho Airport",
      "city_name": "Khajuraho"
    },
    {
      "IATA_code": "AGR",
      "ICAO_code": "VIAG",
      "airport_name": "Kheria Airport",
      "city_name": "Agra"
    },
    {
      "IATA_code": "IXN",
      "ICAO_code": "VEKW",
      "airport_name": "Khowai Airport",
      "city_name": "Khowai"
    },
    {
      "IATA_code": "KLH",
      "ICAO_code": "VAKP",
      "airport_name": "Kolhapur Airport",
      "city_name": "Kolhapur"
    },
    {
      "IATA_code": "KTU",
      "ICAO_code": "VIKO",
      "airport_name": "Kota Airport",
      "city_name": "Kota"
    },
    {
      "IATA_code": "CCJ",
      "ICAO_code": "VOCL",
      "airport_name": "Kozhikode Airport",
      "city_name": "Kozhikode"
    },
    {
      "IATA_code": "KUU",
      "ICAO_code": "VIBR",
      "airport_name": "Kullu Manali Airport",
      "city_name": "Bhuntar Kullu."
    },
    {
      "IATA_code": "IXS",
      "ICAO_code": "VEKU",
      "airport_name": "Kumbhirgram Airport",
      "city_name": "Silchar"
    },
    {
      "IATA_code": "IXI",
      "ICAO_code": "VELR",
      "airport_name": "Lilabari Airport",
      "city_name": "Lilabari"
    },
    {
      "IATA_code": "PNQ",
      "ICAO_code": "VAPO",
      "airport_name": "Lohegaon Airport",
      "city_name": "Pune"
    },
    {
      "IATA_code": "IXM",
      "ICAO_code": "VOMD",
      "airport_name": "Madurai Airport",
      "city_name": "Madurai"
    },
    {
      "IATA_code": "LDA",
      "ICAO_code": "VEMH",
      "airport_name": "Malda Airport",
      "city_name": "Malda"
    },
    {
      "IATA_code": "MOH",
      "ICAO_code": "VEMN",
      "airport_name": "Mohanbari Airport",
      "city_name": "Mohanbari"
    },
    {
      "IATA_code": "IMF",
      "ICAO_code": "VEIM",
      "airport_name": "Municipal Airport",
      "city_name": "Imphal"
    },
    {
      "IATA_code": "MZA",
      "ICAO_code": "",
      "airport_name": "Muzaffarnagar Airport",
      "city_name": "Muzaffarnagar"
    },
    {
      "IATA_code": "MZU",
      "ICAO_code": "VEMZ",
      "airport_name": "Muzaffarpur Airport",
      "city_name": "Muzaffarpur"
    },
    {
      "IATA_code": "MYQ",
      "ICAO_code": "VOMY",
      "airport_name": "Mysore Airport",
      "city_name": "Mysore"
    },
    {
      "IATA_code": "NDC",
      "ICAO_code": "VAND",
      "airport_name": "Nanded Airport",
      "city_name": "Nanded"
    },
    {
      "IATA_code": "CCU",
      "ICAO_code": "VECC",
      "airport_name": "Netaji Subhash Chandra Bose International Airport",
      "city_name": "Kolkata"
    },
    {
      "IATA_code": "NVY",
      "ICAO_code": "VONV",
      "airport_name": "Neyveli Airport",
      "city_name": "Neyveli"
    },
    {
      "IATA_code": "OMN",
      "ICAO_code": "",
      "airport_name": "Osmanabad Airport",
      "city_name": "Osmanabad"
    },
    {
      "IATA_code": "PGH",
      "ICAO_code": "VIPT",
      "airport_name": "Pantnagar Airport",
      "city_name": "Pantnagar"
    },
    {
      "IATA_code": "IXT",
      "ICAO_code": "VEPG",
      "airport_name": "Pasighat Airport",
      "city_name": "Pasighat"
    },
    {
      "IATA_code": "IXP",
      "ICAO_code": "VIPK",
      "airport_name": "Pathankot Airport",
      "city_name": "Pathankot"
    },
    {
      "IATA_code": "PAT",
      "ICAO_code": "VEPT",
      "airport_name": "Patna Airport",
      "city_name": "Patna"
    },
    {
      "IATA_code": "CJB",
      "ICAO_code": "VOCB",
      "airport_name": "Peelamedu Airport",
      "city_name": "Coimbatore"
    },
    {
      "IATA_code": "PNY",
      "ICAO_code": "VOPC",
      "airport_name": "Pondicherry Airport",
      "city_name": "Pondicherry"
    },
    {
      "IATA_code": "PBD",
      "ICAO_code": "VAPR",
      "airport_name": "Porbandar Airport",
      "city_name": "Porbandar"
    },
    {
      "IATA_code": "IXZ",
      "ICAO_code": "VOPB",
      "airport_name": "Port Blair Airport",
      "city_name": "Port Blair"
    },
    {
      "IATA_code": "PUT",
      "ICAO_code": "",
      "airport_name": "Puttaparthi Airport",
      "city_name": "Puttaparthi"
    },
    {
      "IATA_code": "RPR",
      "ICAO_code": "VARP",
      "airport_name": "Raipur Airport",
      "city_name": "Raipur"
    },
    {
      "IATA_code": "ATQ",
      "ICAO_code": "VIAR",
      "airport_name": "Raja Sansi Airport",
      "city_name": "Amritsar"
    },
    {
      "IATA_code": "RJA",
      "ICAO_code": "VORY",
      "airport_name": "Rajahmundry Airport",
      "city_name": "Rajahmundry"
    },
    {
      "IATA_code": "RAJ",
      "ICAO_code": "VARK",
      "airport_name": "Rajkot Airport",
      "city_name": "Rajkot"
    },
    {
      "IATA_code": "RJI",
      "ICAO_code": "",
      "airport_name": "Rajouri Airport",
      "city_name": "Rajouri"
    },
    {
      "IATA_code": "RMD",
      "ICAO_code": "",
      "airport_name": "Ramagundam Airport",
      "city_name": "Ramagundam"
    },
    {
      "IATA_code": "RTC",
      "ICAO_code": "VARG",
      "airport_name": "Ratnagiri Airport",
      "city_name": "Ratnagiri"
    },
    {
      "IATA_code": "REW",
      "ICAO_code": "",
      "airport_name": "Rewa Airport",
      "city_name": "Rewa"
    },
    {
      "IATA_code": "RRK",
      "ICAO_code": "VERK",
      "airport_name": "Rourkela Airport",
      "city_name": "Rourkela"
    },
    {
      "IATA_code": "JRH",
      "ICAO_code": "VEJT",
      "airport_name": "Rowriah Airport",
      "city_name": "Jorhat"
    },
    {
      "IATA_code": "BHJ",
      "ICAO_code": "VABJ",
      "airport_name": "Rudra Mata Airport",
      "city_name": "Bhuj"
    },
    {
      "IATA_code": "RUP",
      "ICAO_code": "VERU",
      "airport_name": "Rupsi Airport",
      "city_name": "Rupsi"
    },
    {
      "IATA_code": "SXV",
      "ICAO_code": "VOSM",
      "airport_name": "Salem Airport",
      "city_name": "Salem"
    },
    {
      "IATA_code": "TEZ",
      "ICAO_code": "VETZ",
      "airport_name": "Salonibari Airport",
      "city_name": "Tezpur"
    },
    {
      "IATA_code": "IXG",
      "ICAO_code": "VABM",
      "airport_name": "Sambre Airport",
      "city_name": "Belgaum"
    },
    {
      "IATA_code": "JAI",
      "ICAO_code": "VIJP",
      "airport_name": "Sanganeer Airport",
      "city_name": "Jaipur"
    },
    {
      "IATA_code": "TNI",
      "ICAO_code": "VIST",
      "airport_name": "Satna Airport",
      "city_name": "Satna"
    },
    {
      "IATA_code": "IXJ",
      "ICAO_code": "VIJU",
      "airport_name": "Satwari Airport",
      "city_name": "Jammu"
    },
    {
      "IATA_code": "SSE",
      "ICAO_code": "VASL",
      "airport_name": "Sholapur Airport",
      "city_name": "Sholapur"
    },
    {
      "IATA_code": "SLV",
      "ICAO_code": "VISM",
      "airport_name": "Simla Airport",
      "city_name": "Simla"
    },
    {
      "IATA_code": "IXA",
      "ICAO_code": "VEAT",
      "airport_name": "Singerbhil Airport",
      "city_name": "Agartala"
    },
    {
      "IATA_code": "IXW",
      "ICAO_code": "VEJS",
      "airport_name": "Sonari Airport",
      "city_name": "Jamshedpur"
    },
    {
      "IATA_code": "NAG",
      "ICAO_code": "VANP",
      "airport_name": "Sonegaon Airport",
      "city_name": "Nagpur"
    },
    {
      "IATA_code": "SXR",
      "ICAO_code": "VISR",
      "airport_name": "Srinagar Airport",
      "city_name": "Srinagar"
    },
    {
      "IATA_code": "STV",
      "ICAO_code": "VASU",
      "airport_name": "Surat Airport",
      "city_name": "Surat"
    },
    {
      "IATA_code": "TEI",
      "ICAO_code": "VETJ",
      "airport_name": "Tezu Airport",
      "city_name": "Tezu"
    },
    {
      "IATA_code": "TJV",
      "ICAO_code": "VOTJ",
      "airport_name": "Thanjavur Airport",
      "city_name": "Thanjavur"
    },
    {
      "IATA_code": "TRV",
      "ICAO_code": "VOTV",
      "airport_name": "Thiruvananthapuram International Airport",
      "city_name": "Trivandrum"
    },
    {
      "IATA_code": "TIR",
      "ICAO_code": "VOTP",
      "airport_name": "Tirupati Airport",
      "city_name": "Tirupati"
    },
    {
      "IATA_code": "TRZ",
      "ICAO_code": "VOTR",
      "airport_name": "Trichy Airport",
      "city_name": "Trichy"
    },
    {
      "IATA_code": "TCR",
      "ICAO_code": "",
      "airport_name": "Tuticorin Airport",
      "city_name": "Tuticorin"
    },
    {
      "IATA_code": "BDQ",
      "ICAO_code": "VABO",
      "airport_name": "Vadodara Airport",
      "city_name": "Vadodara"
    },
    {
      "IATA_code": "VNS",
      "ICAO_code": "VIBN",
      "airport_name": "Varanasi Airport",
      "city_name": "Varanasi"
    },
    {
      "IATA_code": "VGA",
      "ICAO_code": "VOBZ",
      "airport_name": "Vijayawada Airport",
      "city_name": "Vijayawada"
    },
    {
      "IATA_code": "VTZ",
      "ICAO_code": "VEVZ",
      "airport_name": "Vishakhapatnam Airport",
      "city_name": "Vishakhapatnam"
    },
    {
      "IATA_code": "WGC",
      "ICAO_code": "VOWA",
      "airport_name": "Warangal Airport",
      "city_name": "Warangal"
    },
    {
      "IATA_code": "ZER",
      "ICAO_code": "VEZO",
      "airport_name": "Zero Airport",
      "city_name": "Zero"
    }
  ]
}
const airlines = {
  "1T": "Bulgarian Air Charter",
  "Q5": "40-Mile Air",
  "4O": "Interjet",
  "7A": "Express Air Cargo",
  "JY": "Air Turks and Caicos",
  "JU": "Air Serbia",
  "QH": "Kyrgyzstan",
  "A8": "Benin Golf Air",
  "RV": "Caspian Airlines",
  "1B": "Abacus International",
  "W9": "Eastwind Airlines",
  "6U": "Air Ukraine",
  "E4": "Aero Asia International",
  "ZI": "Aigle Azur",
  "AE": "Mandarin Airlines",
  "OZ": "Ozark Air Lines",
  "8U": "Afriqiyah Airways",
  "Q9": "Afrinat International Airlines",
  "KI": "Adam Air",
  "QB": "Georgian National Airlines",
  "LD": "Air Hong Kong",
  "UX": "Air Europa",
  "NX": "Air Macau",
  "ZV": "Air Midwest",
  "HM": "Air Seychelles",
  "AF": "Air France",
  "SB": "Air Caledonie International",
  "EH": "SAETA",
  "ZW": "Air Wisconsin",
  "GN": "Air Gabon",
  "NQ": "Air Japan",
  "VD": "SwedJet Airways",
  "TT": "Tigerair Australia",
  "4N": "Air North Charter - Canada",
  "NZ": "Eagle Airways",
  "QM": "Air Malawi",
  "ML": "Midway Airlines (1976–1991)",
  "P8": "Pantanal Linhas Aéreas",
  "BM": "BMI Regional",
  "ZX": "Air Georgian",
  "G8": "Gujarat Airways",
  "7T": "Tobruk Air",
  "6V": "Mars RK",
  "NH": "All Nippon Airways",
  "TZ": "ATA Airlines",
  "2Q": "Air Cargo Carriers",
  "V7": "Volotea",
  "AB": "Air Berlin",
  "4D": "Air Sinai",
  "QN": "Air Armenia",
  "AI": "Air India Limited",
  "PJ": "Air Saint Pierre",
  "SZ": "Air Southwest",
  "8C": "Shanxi Airlines",
  "NF": "Air Vanuatu",
  "ZB": "Monarch Airlines",
  "CC": "Macair Airlines",
  "RB": "Syrian Arab Airlines",
  "TN": "Air Tahiti Nui",
  "SW": "Air Namibia",
  "AW": "Dirgantara Air Service",
  "PE": "People's Viennaline",
  "JM": "Jetstar Hong Kong Airways",
  "6G": "Air Wales",
  "TX": "Transportes Aéreos Nacionales",
  "IX": "Air India Express",
  "BT": "Air Baltic",
  "EL": "Ellinair",
  "YW": "Air Nostrum",
  "PX": "Air Niugini",
  "G9": "Air Arabia",
  "AC": "Air Canada",
  "AP": "Air One",
  "XT": "SkyStar Airways",
  "UM": "Air Zimbabwe",
  "S2": "Air Sahara",
  "TC": "Air Tanzania",
  "2J": "Air Burkina",
  "KM": "Air Malta",
  "YT": "Air Togo",
  "G4": "Allegiant Air",
  "M3": "North Flying",
  "O4": "Antrak Air",
  "GB": "ABX Air",
  "8V": "Wright Air Service",
  "8T": "Air Tindi",
  "JP": "Adria Airways",
  "A3": "Aegean Airlines",
  "2K": "Aerogal",
  "KD": "KD Avia",
  "KO": "Alaska Central Express",
  "VX": "Virgin America",
  "KH": "Aloha Air Cargo",
  "AA": "American Airlines",
  "AX": "Trans States Airlines",
  "AN": "Ansett Australia",
  "5W": "Astraeus",
  "VV": "Aerosvit Airlines",
  "WK": "Edelweiss Air",
  "QQ": "Reno Air",
  "FG": "Ariana Afghan Airlines",
  "Y2": "Flyglobespan",
  "SU": "Aeroflot Russian Airlines",
  "5Z": "VivaColombia",
  "5D": "DonbassAero",
  "1A": "Amadeus IT Group",
  "JJ": "LATAM Brasil",
  "PL": "Airstars",
  "8A": "Atlas Blue",
  "GD": "Air Alpha Greenland",
  "HT": "Aeromist-Kharkiv",
  "J2": "Azerbaijan Airlines",
  "U3": "Avies",
  "4Y": "Yute Air Alaska",
  "5A": "Alpine Air Express",
  "W4": "Aero Services Executive",
  "IZ": "Arkia Israel Airlines",
  "M6": "Amerijet International",
  "4A": "Air Kiribati",
  "EV": "ExpressJet",
  "HP": "Phoenix Airways",
  "VH": "Aeropostal Alas de Venezuela",
  "AM": "Aeroméxico",
  "TL": "Trans Mediterranean Airlines",
  "OY": "Omni Air International",
  "IW": "Wings Air",
  "J6": "AVCOM",
  "2D": "Aero VIP",
  "VB": "VIVA Aerobus",
  "OE": "Asia Overnight Express",
  "GV": "Aero Flight",
  "JW": "Vanilla Air",
  "2B": "Aerocondor",
  "4C": "Aires, Aerovías de Integración Regional, S.A.",
  "AR": "Aerolíneas Argentinas",
  "AS": "Alaska Airlines, Inc.",
  "OB": "Oasis International Airlines",
  "HC": "Iceland Express",
  "FO": "Airlines of Tasmania",
  "OS": "Austrian Airlines",
  "IQ": "Augsburg Airways",
  "RU": "SkyKing Turks and Caicos Airways",
  "MO": "Calm Air",
  "GR": "Gemini Air Cargo",
  "NO": "Neos",
  "AU": "Austral Líneas Aéreas",
  "AO": "Australian Airlines",
  "AV": "Avianca - Aerovías del Continente Americano S.A.",
  "A0": "Avianca Argentina",
  "O6": "Avianca Brazil",
  "K8": "Airlink Zambia",
  "B9": "Air Bangladesh",
  "HJ": "Hellas Jet",
  "AK": "Air Bridge Carriers",
  "D7": "FlyAsianXpress",
  "DJ": "Polynesian Blue",
  "I5": "AirAsia India",
  "EX": "Air Santo Domingo",
  "3G": "Atlant-Soyuz Airlines",
  "AZ": "Alitalia",
  "ZE": "Líneas Aéreas Azteca",
  "A2": "Cielos Airlines",
  "R7": "Aserca Airlines",
  "RX": "Aviaexpress",
  "MQ": "American Eagle Airlines",
  "ZS": "Sama Airlines",
  "FF": "Airshop",
  "VU": "Air Ivoire",
  "BP": "Air Botswana",
  "GS": "Tianjin Airlines",
  "VT": "Air Tahiti",
  "3N": "Air Urga",
  "VL": "Air VIA",
  "FK": "Keewatin Air",
  "G2": "Avirex",
  "V8": "Iliamna Air Taxi",
  "K6": "Khalifa Airways",
  "VE": "C.A.I. Second",
  "V5": "Royal Aruban Airlines",
  "CA": "Air China",
  "Q6": "Aero Condor Peru",
  "5F": "Fly One",
  "QC": "Air Corridor",
  "NV": "Air Central",
  "CV": "Cargolux",
  "CW": "Air Marshall Islands",
  "ZA": "Interavia Airlines",
  "AH": "Air Algérie",
  "ER": "Astar Air Cargo",
  "HO": "Juneyao Airlines",
  "EN": "Air Dolomiti",
  "NM": "Mount Cook Airlines",
  "EE": "Aero Airlines",
  "4F": "Air City",
  "EI": "Aer Lingus",
  "E8": "Alpi Eagles",
  "KY": "Air São Tomé and Príncipe",
  "PC": "Pegasus Airlines",
  "OF": "Transports et Travaux Aériens de Madagascar",
  "FJ": "Fiji Airways",
  "RC": "Atlantic Airways",
  "NY": "Air Iceland",
  "2P": "Air Philippines",
  "2U": "Air Guinee Express",
  "0A": "Amber Air",
  "DA": "Air Georgia",
  "GL": "Miami Air International",
  "LL": "Allegro",
  "5Y": "Atlas Air",
  "GG": "Cargo 360",
  "H9": "Izair",
  "HD": "AIRDO",
  "IP": "Atyrau Air Ways",
  "QK": "Air Canada Jazz",
  "KK": "Atlasjet",
  "JS": "Air Koryo",
  "KC": "Air Astana",
  "LV": "Albanian Airlines",
  "3S": "Air Guyane Express",
  "D4": "Alidaunia",
  "9I": "Thai Sky Airlines",
  "XL": "Aerolane",
  "A6": "Hongtu Airlines",
  "TD": "Tulip Air",
  "L8": "Air Luxor GB",
  "LK": "Air Luxor",
  "MK": "Air Mauritius",
  "MD": "Air Madagascar",
  "9U": "Air Moldova",
  "L9": "Teamline Air",
  "A7": "Air Plus Comet",
  "QO": "Origin Pacific Airways",
  "MR": "Air Mauritanie",
  "F4": "Albarka Air",
  "AJ": "Aero Contractors",
  "8Y": "China Postal Airlines",
  "OT": "Aeropelican Air Services",
  "AD": "Azul Linhas Aéreas Brasileiras",
  "QD": "Air Class Líneas Aéreas",
  "QS": "Travel Service",
  "AG": "",
  "MC": "Air Mobility Command",
  "RE": "Stobart Air",
  "UU": "Air Austral",
  "ZP": "Silk Way Airlines",
  "6K": "Asian Spirit",
  "A5": "Hop!",
  "QL": "Línea Aérea de Servicio Ejecutivo Regional",
  "R3": "Yakutia Airlines",
  "MV": "Armenian International Airways",
  "2O": "Air Salone",
  "U8": "Armavia",
  "BQ": "Baltia Air Lines",
  "P5": "AeroRepública",
  "BF": "Bluebird Cargo",
  "5L": "AeroSur",
  "JR": "Aero California",
  "Z3": "Avient Aviation",
  "GM": "Air Slovakia",
  "VW": "Aeromar",
  "OR": "TUI Airlines Netherlands",
  "CG": "Airlines PNG",
  "TY": "Iberworld",
  "FL": "AirTran Airways",
  "TS": "Air Transat",
  "EC": "Avialeasing Aviation Company",
  "DW": "Aero-Charter Ukraine",
  "U7": "USA Jet Airlines",
  "6R": "Alrosa Air Company",
  "6A": "Aviacsa",
  "JZ": "Skyways Express",
  "AQ": "MAP-Management and Planung",
  "3J": "Zip",
  "SM": "Swedline Express",
  "KJ": "British Mediterranean Airways",
  "BX": "Coast Air",
  "YE": "Aryan Cargo Express",
  "VJ": "Vietjet Air",
  "3O": "Air Arabia Maroc",
  "X9": "Avion Express",
  "JD": "Beijing Capital Airlines",
  "ID": "Interlink Airlines",
  "BA": "British Airways",
  "BG": "Biman Bangladesh Airlines",
  "B4": "Bankair",
  "WX": "CityJet",
  "BZ": "Keystone Air Service",
  "JA": "JetSMART",
  "J4": "Jordan International Air Cargo",
  "8H": "BH Air",
  "4T": "Belair Airlines",
  "UP": "Bahamasair",
  "E6": "Bringer Air Cargo Taxi Aéreo",
  "LZ": "Balkan Bulgarian Airlines",
  "TH": "Transmile Air Services",
  "BS": "British International Helicopters",
  "PG": "Bangkok Airways",
  "KF": "Blue1",
  "JV": "Bearskin Lake Air Service",
  "B3": "Bellview Airlines",
  "BD": "BMI",
  "WW": "WOW air",
  "CH": "Bemidji Airlines",
  "BO": "Bouraq Indonesia Airlines",
  "BV": "Blue Panorama Airlines",
  "7R": "BRA-Transportes Aéreos",
  "8E": "Bering Air",
  "B2": "Belavia Belarusian Airlines",
  "BN": "Horizon Airlines",
  "GQ": "Big Sky Airlines",
  "V9": "Star1 Airlines",
  "Y6": "Batavia Air",
  "BU": "Buryat Airlines Aircompany",
  "J8": "Berjaya Air",
  "QW": "Blue Wings",
  "SN": "Brussels Airlines",
  "DB": "Brit Air",
  "E9": "Boston-Maine Airways",
  "NT": "Binter Canarias",
  "0B": "Blue Air",
  "FB": "Bulgaria Air",
  "8N": "Barents AirLink",
  "CJ": "CityFlyer Express",
  "YB": "Borajet",
  "BW": "Caribbean Airlines",
  "7N": "PAWA Dominicana",
  "5C": "CAL Cargo Air Lines",
  "3C": "RegionsAir",
  "R9": "Camai Air",
  "UY": "Cameroon Airlines",
  "C6": "CanJet",
  "CP": "Compass Airlines",
  "5T": "Canadian North",
  "W2": "Canadian Western Airlines",
  "9K": "Cape Air",
  "PT": "West Air Sweden",
  "2G": "Cargoitalia",
  "W8": "Cargojet Airways",
  "C8": "Chicago Express Airlines",
  "8B": "Caribbean Star Airlines",
  "V3": "Carpatair",
  "CX": "Cathay Pacific",
  "KX": "Cayman Airways",
  "5J": "Cebu Pacific",
  "3B": "Central Connect Airlines",
  "9M": "Central Mountain Air",
  "J7": "ValuJet Airlines",
  "WE": "Thai Smile Airways",
  "OP": "Chalk's International Airlines",
  "MG": "Champion Air",
  "2Z": "Chang An Airlines",
  "S8": "Skywise Airline",
  "CI": "China Airlines",
  "CK": "China Cargo Airlines",
  "MU": "China Eastern Airlines",
  "G5": "China Express Airlines",
  "WH": "WebJet Linhas Aéreas",
  "CZ": "China Southern Airlines",
  "KN": "China United Airlines",
  "XO": "LTE International Airways",
  "3Q": "China Yunnan Airlines",
  "X7": "Chitaavia",
  "QI": "Cimber Sterling",
  "C7": "Rico Linhas Aéreas",
  "C9": "Cirrus Airlines",
  "CF": "City Airline",
  "G3": "Gol Transportes Aéreos",
  "CT": "Civil Air Transport",
  "6P": "Club Air",
  "DQ": "Coastal Air",
  "9L": "Colgan Air",
  "YD": "Cologne Air Transport GmbH",
  "OH": "PSA Airlines",
  "MN": "Comair",
  "C5": "CommutAir",
  "KR": "Comores Airlines",
  "GJ": "Eurofly",
  "DE": "Condor Flugdienst",
  "CO": "Continental Express",
  "CS": "Continental Micronesia",
  "V0": "Conviasa",
  "CM": "Copa Airlines",
  "CQ": "Sunshine Express Airlines",
  "XC": "Corendon Airlines",
  "CD": "Corendon Dutch Airlines",
  "SS": "Corsairfly",
  "XK": "Corse Méditerranée",
  "F5": "Cosmic Air",
  "OU": "Croatia Airlines",
  "7C": "Jeju Air",
  "QE": "Crossair Europe",
  "CU": "Cubana de Aviación",
  "CY": "Cyprus Airways",
  "YK": "Cyprus Turkish Airlines",
  "OK": "Czech Airlines",
  "8L": "Redhill Aviation",
  "XG": "Clickair",
  "WD": "WDL Aviation",
  "DX": "DAT Danish Air Transport",
  "ES": "DHL International",
  "L3": "LTU Austria",
  "D3": "Daallo Airlines",
  "N2": "Kabo Air",
  "H8": "Dalavia",
  "0D": "Darwin Airline",
  "D5": "Dauair",
  "DL": "Delta Air Lines",
  "2A": "Deutsche Bahn",
  "1I": "Sky Trek International Airlines",
  "DH": "Independence Air",
  "Z6": "Dniproavia",
  "YU": "Dominair",
  "DO": "Dominicana de Aviación",
  "E3": "Domodedovo Airlines",
  "D9": "Donavia",
  "KA": "Dragonair, Hong Kong Dragon Airlines",
  "KB": "Druk Air",
  "DI": "Dba",
  "9A": "Eagle Express Air Charter",
  "E1": "Everbread",
  "1C": "Electronic Data Systems",
  "1Y": "Electronic Data Systems",
  "BR": "EVA Air",
  "EY": "Etihad Airways",
  "H7": "Eagle Air",
  "QU": "Uganda Airlines",
  "S9": "East African Safari Air",
  "EA": "European Air Express",
  "T3": "Eastern Airways",
  "QF": "Sunstate Airlines",
  "DK": "Eastland Air",
  "MS": "Egyptair",
  "LY": "El Al Israel Airlines",
  "UZ": "El-Buraq Air Transport",
  "EK": "Emirates Airlines",
  "EM": "Empire Airlines",
  "EU": "Empresa Ecuatoriana De Aviación",
  "E0": "Eos Airlines",
  "B8": "Eritrean Airlines",
  "E7": "European Aviation Air Charter",
  "OV": "SalamAir",
  "ET": "Ethiopian Airlines",
  "RZ": "Euro Exec Express",
  "MM": "SAM Colombia",
  "UI": "Eurocypria Airlines",
  "K2": "Eurolot",
  "3W": "Euromanx Airways",
  "5O": "Europe Airpost",
  "QY": "European Air Transport",
  "EW": "Eurowings",
  "EZ": "Sun Air of Scandinavia",
  "JN": "Excel Airways",
  "MB": "MNG Airlines",
  "OW": "Executive Airlines",
  "EO": "Hewa Bora Airways",
  "U2": "United Feeder Service",
  "DS": "easyJet Switzerland",
  "IH": "Irtysh Air",
  "EF": "Far Eastern Air Transport",
  "FD": "Thai AirAsia",
  "F6": "FaroeJet",
  "F3": "Faso Airways",
  "FX": "Federal Express",
  "N8": "National Air Cargo dba National Airlines",
  "4S": "Finalair Congo",
  "AY": "Finnair",
  "FC": "Finncomm Airlines",
  "FY": "Northwest Regional Airlines",
  "7F": "First Air",
  "DP": "First Choice Airways",
  "8F": "Fischer Air",
  "8D": "Servant Air",
  "B5": "Flightline",
  "PA": "Pan American World Airways",
  "RF": "Florida West International Airways",
  "F2": "Fly Air",
  "OJ": "Overland Airways",
  "SH": "Fly Me Sweden",
  "TE": "Skytaxi",
  "LF": "FlyNordic",
  "F7": "Flybaboo",
  "BE": "Flybe",
  "W3": "Switfair Cargo",
  "VY": "Vueling Airlines",
  "HK": "Four Star Aviation / Four Star Cargo",
  "FH": "Futura International Airways",
  "SJ": "Freedom Air",
  "FP": "Servicios Aéreos de los Andes",
  "F9": "Frontier Airlines",
  "2F": "Frontier Flying Service",
  "FZ": "Flydubai",
  "9Y": "Fly Georgia",
  "VK": "Virgin Nigeria Airways",
  "GX": "Pacificair",
  "Y5": "Pace Airlines",
  "GT": "GB Airways",
  "Z5": "GMG Airlines",
  "7O": "Galaxy Air",
  "1G": "Galileo International",
  "GC": "Gambia International Airlines",
  "G7": "GoJet Airlines",
  "GA": "Garuda Indonesia",
  "4G": "Gazpromavia",
  "A9": "Georgian Airways",
  "ST": "Germania",
  "4U": "Germanwings",
  "GP": "Palau Trans Pacific Airlines",
  "GH": "Ghana Airways",
  "G0": "Ghana International Airlines",
  "GK": "JetStar Japan",
  "DC": "Golden Air",
  "G1": "Gorkha Airlines",
  "ZK": "Great Lakes Airlines",
  "IJ": "Spring Airlines Japan",
  "G6": "Air Volga",
  "J9": "Jazeera Airways",
  "GF": "Gulf Air Bahrain",
  "GY": "Tri-MG Intra Asia Airlines",
  "H6": "Hageland Aviation Services",
  "HR": "Hahn Air",
  "HU": "Hainan Airlines",
  "1R": "Hainan Phoenix Information Systems",
  "2T": "Haiti Ambassador Airlines",
  "4R": "Hamburg International",
  "X3": "Hapag-Lloyd Express (TUIfly)",
  "HF": "Hapagfly",
  "HB": "Harbor Airlines",
  "HQ": "Thomas Cook Airlines",
  "HA": "Hawaiian Airlines",
  "BH": "Hawkair",
  "HN": "Heavylift Cargo Airlines",
  "JB": "Helijet",
  "ZU": "Helios Airways",
  "HW": "North-Wright Airways",
  "2L": "Helvetic Airways",
  "UD": "Hex'Air",
  "5K": "Hi Fly",
  "H5": "Mavial Magadan Airlines",
  "HX": "Hong Kong Airlines",
  "RH": "Republic Express Airlines",
  "UO": "Hong Kong Express Airways",
  "HH": "Hope Air",
  "QX": "Horizon Air",
  "H4": "Inter Island Airways",
  "IK": "Lankair",
  "II": "IBC Airways",
  "0C": "IBL Aviation",
  "C3": "Independent Carrier (ICAR)",
  "1F": "INFINI Travel Information",
  "1U": "Polyot Sirena",
  "IB": "Iberia Airlines",
  "I2": "Iberia Express",
  "FW": "Ibex Airlines",
  "FI": "Icelandair",
  "6E": "IndiGo Airlines",
  "IC": "Indian Airlines",
  "I9": "Indigo Airlines",
  "QZ": "Indonesia AirAsia",
  "IO": "Indonesian Airlines",
  "D6": "Interair South Africa",
  "RS": "Sky Regional Airlines",
  "6I": "International Business Air",
  "3L": "Intersky",
  "I4": "Interstate Airlines",
  "IR": "Iran Air",
  "EP": "Iran Aseman Airlines",
  "IA": "Iraqi Airways",
  "2S": "Satgur Air Transport",
  "CN": "Westward Airways",
  "IF": "Islas Airways",
  "WC": "Islena De Inversiones",
  "6H": "Israir",
  "FS": "Servicios de Transportes Aéreos Fueguinos",
  "GI": "Itek Air",
  "XM": "J-Air",
  "JC": "JAL Express",
  "JO": "Jettime",
  "MT": "Thomas Cook Airlines",
  "1M": "JSC Transport Automated Information Systems",
  "JI": "Midway Airlines (1993–2003)",
  "3X": "Japan Air Commuter",
  "JL": "Japan Airlines Domestic",
  "EG": "Japan Asia Airways",
  "NU": "Japan Transocean Air",
  "O2": "Linear Air",
  "9W": "Jet Airways",
  "QJ": "Jet Airways",
  "PP": "Jet Aviation",
  "3K": "Jetstar Asia Airways",
  "LS": "Jet2.com",
  "B6": "JetBlue Airways",
  "JF": "L.A.B. Flying Service",
  "0J": "Jetclub",
  "SG": "Spicejet",
  "JQ": "Jetstar Airways",
  "JX": "Jett8 Airlines Cargo",
  "R5": "Malta Air Charter",
  "6J": "Skynet Asia Airways",
  "KW": "Wataniya Airways",
  "WA": "Western Airlines",
  "KL": "KLM",
  "K4": "Kalitta Air",
  "K9": "Krylo Airlines",
  "RQ": "Kam Air",
  "E2": "Rio Grande Air",
  "V2": "Vision Airlines",
  "KV": "Kavminvodyavia",
  "M5": "Kenmore Air",
  "KQ": "Kenya Airways",
  "IT": "Tigerair Taiwan",
  "Y9": "Kish Air",
  "KP": "Kiwi International Air Lines",
  "7K": "Kogalymavia Air Company",
  "8J": "Komiinteravia",
  "KE": "Korean Air",
  "7B": "Krasnojarsky Airlines",
  "GW": "SkyGreece Airlines",
  "KU": "Kuwait Airways",
  "GO": "Kuzu Airlines Cargo",
  "N5": "Skagway Air Service",
  "R8": "Kyrgyzstan Airlines",
  "YQ": "TAR Aerolineas",
  "LR": "LACSA",
  "KG": "LAI - Línea Aérea IAACA",
  "LA": "LATAM Chile",
  "4M": "LATAM Argentina",
  "PZ": "TAM Mercosur",
  "LU": "LATAM Express",
  "LP": "LATAM Peru",
  "NI": "Portugalia",
  "L5": "Lufttransport",
  "LO": "LOT Polish Airlines",
  "LT": "LongJiang Airlines",
  "N6": "Nuevo Continente",
  "QV": "Lao Airlines",
  "L7": "Línea Aérea SAPSA",
  "NG": "Lauda Air",
  "LQ": "Lebanese Air Transport",
  "LI": "Leeward Islands Air Transport",
  "LN": "Libyan Arab Airlines",
  "TM": "Linhas Aéreas de Moçambique",
  "JT": "Lion Mentari Airlines",
  "LM": "Livingston",
  "LB": "Lloyd Aéreo Boliviano",
  "LC": "Varig Logística",
  "HE": "Luftfahrtgesellschaft Walter",
  "LH": "Lufthansa Cargo",
  "CL": "Lufthansa CityLine",
  "L1": "Lufthansa Systems",
  "DV": "Nantucket Airlines",
  "LG": "Luxair",
  "5V": "Lviv Airlines",
  "L2": "Lynden Air Cargo",
  "L4": "Lynx Aviation",
  "Z8": "Línea Aérea Amaszonas",
  "MJ": "Mihin Lanka",
  "Q2": "Maldivian (airline)",
  "OD": "Malindo Airways",
  "M7": "Tropical Airways",
  "MH": "Malaysia Airlines",
  "IN": "NAM Air",
  "OM": "MIAT Mongolian Airlines",
  "DM": "Maersk",
  "W5": "Mahan Air",
  "M2": "MHS Aviation GmbH",
  "TF": "Malmö Aviation",
  "MA": "Malév Hungarian Airlines",
  "RI": "Mandala Airlines",
  "JE": "Mango",
  "MP": "Martinair",
  "Q4": "Starlink Aviation",
  "8M": "Myanmar Airways International",
  "MY": "Midwest Airlines (Egypt)",
  "MW": "Mokulele Airlines",
  "7M": "Mayair",
  "M8": "Mekong Airlines",
  "IM": "Menajet",
  "IG": "Meridiana",
  "MZ": "Merpati Nusantara Airlines",
  "YV": "Mesa Airlines",
  "XJ": "Thai AirAsia X",
  "MX": "Mexicana de Aviación",
  "ME": "Middle East Airlines",
  "YX": "Midwest Airlines",
  "M4": "Mistral Air",
  "2M": "Moldavian Airlines",
  "8I": "Myway Airlines",
  "YM": "Montenegro Airlines",
  "5M": "Sibaviatrans",
  "3R": "Moskovia Airlines",
  "M9": "Motor Sich",
  "N4": "Nordwind Airlines",
  "VZ": "Thai Vietjet Air",
  "UB": "Myanma Airways",
  "6N": "Nordic Regional",
  "P9": "Peruvian Airlines",
  "UE": "Transeuropean Airlines",
  "N7": "National Airlines",
  "NA": "North American Airlines",
  "9O": "National Airways Cameroon",
  "NC": "Northern Air Cargo",
  "CE": "Nationwide Airlines",
  "1N": "Navitaire",
  "RA": "Nepal Airlines",
  "EJ": "New England Airlines",
  "2N": "Yuzhmashavia",
  "HG": "Niki",
  "KZ": "Nippon Cargo Airlines",
  "DD": "Nok Air",
  "5N": "Nordavia",
  "JH": "Nordeste Linhas Aéreas Regionais",
  "N9": "North Coast Aviation",
  "NW": "Northwest Airlines",
  "J3": "Northwestern Air",
  "DY": "Norwegian Air Shuttle",
  "D8": "Norwegian Air International",
  "DU": "Norwegian Long Haul",
  "BJ": "Nouvel Air Tunisie",
  "O9": "Nova Airline",
  "VQ": "Novo Air",
  "NK": "Spirit Airlines",
  "UQ": "O'Connor Airlines",
  "O8": "Oasis Hong Kong Airlines",
  "VC": "Voyageur Airways",
  "OA": "Olympic Airlines",
  "WY": "Oman Air",
  "8Q": "Princess Air",
  "R2": "Orenburg Airlines",
  "OX": "Orient Thai Airlines",
  "OL": "OLT Express Germany",
  "ON": "Our Airline",
  "O7": "Ozjet Airlines",
  "PV": "St Barth Commuter",
  "9Q": "PB Air",
  "PU": "PLUNA",
  "U4": "PMTair",
  "BL": "Pacific Airlines",
  "8P": "Pacific Coastal Airlines",
  "Q8": "Pacific East Asia Cargo Airlines",
  "LW": "Sun Air International",
  "PK": "Pakistan International Airlines",
  "PF": "Palestinian Airlines",
  "NR": "Pamir Airways",
  "PN": "Pan American Airways",
  "I7": "Paramount Airways",
  "P3": "Passaredo Transportes Aéreos",
  "KS": "Peninsula Airways",
  "Z2": "EZD",
  "PR": "Philippine Airlines",
  "9R": "Phuket Air",
  "PI": "Sun Air (Fiji)",
  "9E": "Pinnacle Airlines",
  "PO": "Polar Air Cargo",
  "PH": "Polynesian Airlines",
  "PD": "Porter Airlines",
  "BK": "Potomac Air",
  "PW": "Precision Air",
  "TO": "Transavia France",
  "FE": "Primaris Airlines",
  "8W": "Private Wings Flugcharter",
  "P6": "Privilege Style Líneas Aéreas",
  "P0": "Proflight Zambia",
  "FV": "Rossiya",
  "QR": "Qatar Airways",
  "R6": "RACSA",
  "1D": "Radixx Solutions International",
  "V4": "Vieques Air Link",
  "FN": "Regional Air Lines",
  "ZL": "Regional Express",
  "P7": "Russian Sky Airlines",
  "RW": "Republic Airlines",
  "RL": "Royal Phnom Penh Airways",
  "SL": "Thai Lion Mentari",
  "GZ": "Air Rarotonga",
  "RR": "Royal Air Force",
  "AT": "Royal Air Maroc",
  "R0": "Royal Airlines",
  "BI": "Royal Brunei Airlines",
  "RJ": "Royal Jordanian",
  "RK": "Royal Khmer Airlines",
  "WR": "WestJet Encore",
  "WB": "Rwandair Express",
  "7S": "Ryan Air Service",
  "RD": "Ryan International Airlines",
  "FR": "Ryanair",
  "YS": "Régional Compagnie Aérienne Européenne",
  "TR": "Tigerair Singapore",
  "6Y": "Smartlynx Airlines",
  "7E": "Sylt Air GmbH",
  "S4": "SATA International",
  "SA": "South African Airways",
  "W7": "Western Pacific Airlines",
  "NL": "Shaheen Air International",
  "SK": "SAS Braathens",
  "UG": "Tuninter",
  "S7": "S7 Airlines",
  "BB": "Seaborne Airlines",
  "K5": "SeaPort Airlines",
  "UL": "SriLankan Airlines",
  "SY": "Sun Country Airlines",
  "I6": "Sky Eyes",
  "7G": "Star Flyer",
  "FA": "Safair",
  "HZ": "Sat Airlines",
  "SP": "SATA Air Acores",
  "8S": "Scorpio Aviation",
  "ZY": "Sky Airlines",
  "SQ": "Singapore Airlines Cargo",
  "SI": "Skynet Airlines",
  "XS": "SITA",
  "FT": "Siem Reap Airways",
  "SX": "Skybus Airlines",
  "S6": "Star Air",
  "D2": "Severstal Air Company",
  "5G": "Skyservice Airlines",
  "SD": "Sudan Airways",
  "SV": "Saudia",
  "WN": "Southwest Airlines",
  "A4": "Southern Winds Airlines",
  "WG": "Sunwing Airlines",
  "LX": "Swiss International Air Lines",
  "SR": "Swissair",
  "WV": "Swe Fly",
  "XQ": "SunExpress",
  "AL": "TransAVIAexport Airlines",
  "E5": "Samara Airlines",
  "SC": "Shandong Airlines",
  "9C": "Spring Airlines",
  "3U": "Sichuan Airlines",
  "FM": "Shanghai Airlines",
  "ZH": "Shenzhen Airlines",
  "7L": "Sun D'Or",
  "NE": "SkyEurope",
  "SO": "Sunshine Airlines",
  "JK": "Spanair",
  "1Z": "Sabre Pacific",
  "1S": "Sabre",
  "1H": "Siren-Travel",
  "1Q": "Sirena",
  "1K": "Sutra",
  "2C": "SNCF",
  "S0": "Slok Air Gambia",
  "S3": "Santa Barbara Airlines",
  "H2": "Sky Airline",
  "OO": "SkyWest Airlines",
  "BC": "Skymark Airlines",
  "LJ": "Sierra National Airlines",
  "MI": "SilkAir",
  "6Q": "Slovak Airlines",
  "PY": "Surinam Airways",
  "NB": "Sterling Airlines",
  "IE": "Solomon Airlines",
  "6W": "Saratov Airlines Joint Stock Company",
  "S5": "Trast Aero",
  "R1": "Sirin",
  "O3": "SF Airlines",
  "EQ": "TAME",
  "TP": "TAP Portugal",
  "TU": "Tunisair",
  "3V": "TNT Airways",
  "T2": "Thai Air Cargo",
  "TQ": "Tandem Aero",
  "ZT": "Titan Airways",
  "DG": "Tigerair Philippines",
  "TG": "Thai Airways International",
  "TK": "Turkish Airlines",
  "T7": "Twin Jet",
  "3P": "Tiara Air",
  "TI": "Tol-Air Services",
  "BY": "Thomson Airways",
  "PM": "Tropic Air",
  "QT": "TAMPA",
  "K3": "Taquan Air Services",
  "GE": "TransAsia Airways",
  "HV": "Transavia Holland",
  "VR": "TACV",
  "T9": "Thai Star Airlines",
  "9T": "Transwest Air",
  "UN": "Transaero Airlines",
  "T5": "Turkmenhovayollary",
  "T6": "Tavrey Airlines",
  "TW": "T'way Air",
  "6B": "TUIfly Nordic",
  "DT": "TAAG Angola Airlines",
  "SF": "Tassili Airlines",
  "TJ": "Tradewind Aviation",
  "1E": "Travelsky Technology",
  "2H": "Thalys",
  "1L": "Open Skies Consultative Commission",
  "RO": "Tarom",
  "3T": "Turan Air",
  "T4": "TRIP Linhas Aéreas",
  "L6": "Tbilaviamsheni",
  "XN": "XpressAir",
  "VO": "Tyrolean Airways",
  "U5": "USA3000 Airlines",
  "UA": "United Airlines",
  "4H": "United Airways",
  "U6": "Ural Airlines",
  "UF": "UM Airlines",
  "6Z": "Ukrainian Cargo Airways",
  "5X": "United Parcel Service",
  "US": "US Airways",
  "UH": "US Helicopter",
  "UT": "UTair Aviation",
  "HY": "Uzbekistan Airways",
  "PS": "Ukraine International Airlines",
  "VA": "Viasa",
  "VF": "Valuair",
  "0V": "Vietnam Air Services Company (VASCO)",
  "VN": "Vietnam Airlines",
  "NN": "VIM Airlines",
  "2R": "Via Rail Canada",
  "Y4": "Volaris",
  "VI": "Volga-Dnepr Airlines",
  "TV": "Virgin Express",
  "VS": "Virgin Atlantic Airways",
  "ZG": "Viva Macau",
  "XF": "Vladivostok Air",
  "VM": "Viaggio Air",
  "9V": "Vipair Airlines",
  "RG": "VRG Linhas Aéreas",
  "VP": "VASP",
  "VG": "VLM Airlines",
  "WT": "Wasaya Airways",
  "2W": "Welcome Air",
  "WZ": "West African Airlines",
  "YH": "West Caribbean Airways",
  "8O": "West Coast Air",
  "WS": "WestJet",
  "XP": "Xtra Airways",
  "WF": "Widerøe",
  "IV": "Wind Jet",
  "7W": "Windrose Air",
  "8Z": "Wizz Air Bulgaria",
  "W6": "Wizz Air",
  "WO": "World Airways",
  "1P": "Worldspan",
  "MF": "Xiamen Airlines",
  "SE": "XL Airways France",
  "YL": "Yamal Airlines",
  "Y8": "Yangtze River Express",
  "Y0": "Yellow Air Taxi/Friendship Airways",
  "IY": "Yemenia",
  "C4": "Zimex Aviation",
  "Q3": "Zambian Airways",
  "Z4": "Zoom Airlines"
}

export { airportsData,airlines }